### PR TITLE
Add support for tolerations to the deployment

### PR DESCRIPTION
**Pull request by gabor-boros**
I would like to add support for tolerations to the deployment.

### CODE REVIEW

**Comment by gabor-boros** [comment]
Ping @everpeace

**Comment by everpeace** [comment]
Thanks! looks good to me!

**Comment by everpeace** [comment]
@gabor-boros   would you mind updating index file by running `setup.sh` on your branch??

I believe this fixes #8 .

**Comment by gabor-boros** [comment]
@everpeace I ran `build.sh` so the indexes should be updated. Is there anything else what I can do?

**Comment by everpeace** [comment]
@gabor-boros Thanks!!  LGTM! I'm gonna merge it!

**Comment by gabor-boros** [comment]
@everpeace Thank you for merging 🎉

**Pull request merged**
